version: '3.1'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/node.conf:/etc/nginx/conf.d/node.template
    ports:
      - '8080:80'
    command: 'bash -c "cat /etc/nginx/conf.d/node.template > /etc/nginx/conf.d/default.conf && nginx -g ''daemon off;''"'
  node:
    image: node:10.14
    user: node
    working_dir: /whatever
    environment:
      - NODE_ENV=production
    volumes:
      - ./app:/whatever/app
    ports:
      - '3000:3000'
    command: 'npm start'
